<a href="https://colab.research.google.com/github/atakishiyevamalak/MachineLearningProjects/blob/main/Deep_Learning_Tensorflow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
import matplotlib as plt
import tensorflow as tf

In [2]:
print(tf.__version__)

2.19.0


In [3]:
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [4]:
scalar.ndim

0

In [5]:
vector = tf.constant([10, 10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [6]:
vector.ndim

1

In [7]:
matrix = tf.constant([[10, 7],
                     [7, 10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [8]:
matrix.ndim

2

In [9]:
another_matrix = tf.constant([[5., 5.],
                              [5., 5.],
                              [5., 5.]], dtype = tf.float32)
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[5., 5.],
       [5., 5.],
       [5., 5.]], dtype=float32)>

In [11]:
another_matrix.ndim

2

In [12]:
changeable_tensor = tf.Variable([5, 7])
unchangeable_tensor = tf.constant([5, 7])
changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([5, 7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([5, 7], dtype=int32)>)

In [13]:
changeable_tensor[0].assign(2)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([2, 7], dtype=int32)>

In [16]:
random_1 = tf.random.Generator.from_seed(42)    # pyTorch torch.Generator().manual_seed(42)
random_1 = random_1.normal(shape=(3, 3))
random_1

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702,  0.07595026],
       [-1.2573844 , -0.23193763, -1.8107855 ],
       [ 0.09988727, -0.50998646, -0.7535805 ]], dtype=float32)>

In [18]:
not_shuffled = tf.constant([[1, 5],
                           [7, 9],
                           [3, 8]])
not_shuffled

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 5],
       [7, 9],
       [3, 8]], dtype=int32)>

In [19]:
shuffled = tf.random.shuffle(not_shuffled)
shuffled

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[7, 9],
       [1, 5],
       [3, 8]], dtype=int32)>

In [22]:
tf.random.set_seed(42)
tf.random.shuffle(not_shuffled, seed=42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 5],
       [7, 9],
       [3, 8]], dtype=int32)>

In [25]:
tf.ones([3, 4])  #torch.ones()

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float32)>

In [24]:
tf.zeros([3, 4])  #torch.zeros()

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

In [28]:
import numpy as np

numpy_A = np.arange(1, 25, dtype=np.int32)

numpy_A

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [29]:
A = tf.constant(numpy_A, shape=(2, 2, 2, 3))
A

<tf.Tensor: shape=(2, 2, 2, 3), dtype=int32, numpy=
array([[[[ 1,  2,  3],
         [ 4,  5,  6]],

        [[ 7,  8,  9],
         [10, 11, 12]]],


       [[[13, 14, 15],
         [16, 17, 18]],

        [[19, 20, 21],
         [22, 23, 24]]]], dtype=int32)>

In [30]:
zeros = tf.zeros([1, 2, 3, 4, 5, 4])
zeros

<tf.Tensor: shape=(1, 2, 3, 4, 5, 4), dtype=float32, numpy=
array([[[[[[0., 0., 0., 0.],
           [0., 0., 0., 0.],
           [0., 0., 0., 0.],
           [0., 0., 0., 0.],
           [0., 0., 0., 0.]],

          [[0., 0., 0., 0.],
           [0., 0., 0., 0.],
           [0., 0., 0., 0.],
           [0., 0., 0., 0.],
           [0., 0., 0., 0.]],

          [[0., 0., 0., 0.],
           [0., 0., 0., 0.],
           [0., 0., 0., 0.],
           [0., 0., 0., 0.],
           [0., 0., 0., 0.]],

          [[0., 0., 0., 0.],
           [0., 0., 0., 0.],
           [0., 0., 0., 0.],
           [0., 0., 0., 0.],
           [0., 0., 0., 0.]]],


         [[[0., 0., 0., 0.],
           [0., 0., 0., 0.],
           [0., 0., 0., 0.],
           [0., 0., 0., 0.],
           [0., 0., 0., 0.]],

          [[0., 0., 0., 0.],
           [0., 0., 0., 0.],
           [0., 0., 0., 0.],
           [0., 0., 0., 0.],
           [0., 0., 0., 0.]],

          [[0., 0., 0., 0.],
           [0., 0., 0., 0.]

In [31]:
tf.rank(zeros)

<tf.Tensor: shape=(), dtype=int32, numpy=6>

In [32]:
A.shape, A.ndim, tf.size(A), tf.rank(A)

(TensorShape([2, 2, 2, 3]),
 4,
 <tf.Tensor: shape=(), dtype=int32, numpy=24>,
 <tf.Tensor: shape=(), dtype=int32, numpy=4>)

In [33]:
def info_about_tensor(tensor):
  print("Data type of every element: ", tensor.dtype)
  print("Number of dimensions (Rank): ", tf.rank(tensor))
  print("Shape of tensor: ", tensor.shape)
  print("Elements along the 0 axis: ", tensor.shape[0])
  print("Elements along the last axis: ", tensor.shape[-1])
  print("Total number of elements in our tensor: ", tf.size(tensor).numpy())

In [34]:
info_about_tensor(A)

Data type of every element:  <dtype: 'int32'>
Number of dimensions (Rank):  tf.Tensor(4, shape=(), dtype=int32)
Shape of tensor:  (2, 2, 2, 3)
Elements along the 0 axis:  2
Elements along the last axis:  3
Total number of elements in our tensor:  24


In [35]:
rank_2_tensor = tf.ones(shape = (2, 3))
rank_2_tensor

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

In [36]:
tf.rank(rank_2_tensor)

<tf.Tensor: shape=(), dtype=int32, numpy=2>

In [37]:
rank_3_tensor = rank_2_tensor[..., tf.newaxis]
rank_3_tensor

<tf.Tensor: shape=(2, 3, 1), dtype=float32, numpy=
array([[[1.],
        [1.],
        [1.]],

       [[1.],
        [1.],
        [1.]]], dtype=float32)>

In [38]:
tf.expand_dims(rank_2_tensor, axis=2)    # axis hara elave etdiyini gosterir

<tf.Tensor: shape=(2, 3, 1), dtype=float32, numpy=
array([[[1.],
        [1.],
        [1.]],

       [[1.],
        [1.],
        [1.]]], dtype=float32)>

In [39]:
tensor = tf.constant([[10, 6],
                     [6, 9]])
tensor + 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 16],
       [16, 19]], dtype=int32)>

In [42]:
tensor * 10

# or

tf.multiply(tensor, 10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  60],
       [ 60,  90]], dtype=int32)>

In [43]:
tf.matmul(tensor, tensor) # matrix multiplication --> dot product
# or

tensor @ tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[136, 114],
       [114, 117]], dtype=int32)>

In [45]:
X = tf.constant([[1, 2, 3],
                  [4, 5, 6]])
Y = tf.constant([[7, 8, 9],
                 [10, 11, 12]])

X, Y

(<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 2, 3],
        [4, 5, 6]], dtype=int32)>,
 <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[ 7,  8,  9],
        [10, 11, 12]], dtype=int32)>)

In [46]:
Y = tf.transpose(Y)
Y

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 7, 10],
       [ 8, 11],
       [ 9, 12]], dtype=int32)>

In [47]:
X @ Y

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 50,  68],
       [122, 167]], dtype=int32)>

In [48]:
tf.matmul(X, Y)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 50,  68],
       [122, 167]], dtype=int32)>

In [49]:
tf.reshape(Y, shape=(2, 3))

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 7, 10,  8],
       [11,  9, 12]], dtype=int32)>

In [50]:
X, Y

(<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 2, 3],
        [4, 5, 6]], dtype=int32)>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 7, 10],
        [ 8, 11],
        [ 9, 12]], dtype=int32)>)

In [51]:
tf.tensordot(X, Y, axes= 0)

<tf.Tensor: shape=(2, 3, 3, 2), dtype=int32, numpy=
array([[[[ 7, 10],
         [ 8, 11],
         [ 9, 12]],

        [[14, 20],
         [16, 22],
         [18, 24]],

        [[21, 30],
         [24, 33],
         [27, 36]]],


       [[[28, 40],
         [32, 44],
         [36, 48]],

        [[35, 50],
         [40, 55],
         [45, 60]],

        [[42, 60],
         [48, 66],
         [54, 72]]]], dtype=int32)>

In [52]:
tf.tensordot(X, Y, axes=1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 50,  68],
       [122, 167]], dtype=int32)>

In [53]:
A = tf.constant([4, 5])
A.dtype

tf.int32

In [54]:
A = tf.cast(A, dtype=tf.int16)

In [55]:
A.dtype

tf.int16

In [56]:
E = tf.constant(np.random.randint(0, 100, size=50))
E

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([ 8, 93, 69, 86, 51, 35, 70, 52, 62, 79, 99, 41, 12, 80, 52, 37, 29,
       64, 94, 93, 67, 21, 46, 32, 16, 15, 52, 85, 57, 29, 55, 37, 77, 52,
       89, 53, 57, 11, 14, 61,  5, 96, 98, 81, 19, 22, 36,  9, 31, 37])>

In [57]:
E.dtype

tf.int64

In [59]:
tf.random.set_seed(42)
G = tf.constant(tf.random.uniform(shape = [50]), shape = [1, 1, 1, 1, 50])
G

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
           0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
           0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
           0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
           0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
           0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
           0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
           0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
           0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
           0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043]]]]],
      dtype=float32)>

In [61]:
G.dtype

tf.float32

In [62]:
G_squeezed = tf.squeeze(G)
G_squeezed, G_squeezed.shape

(<tf.Tensor: shape=(50,), dtype=float32, numpy=
 array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
        0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
        0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
        0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
        0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
        0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
        0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
        0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
        0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
        0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
       dtype=float32)>,
 TensorShape([50]))